Document: modelloading
Title: Debian modelloading Manual
Author: <insert document author here>
Abstract: This manual describes what modelloading is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/modelloading/modelloading.sgml.gz

Format: postscript
Files: /usr/share/doc/modelloading/modelloading.ps.gz

Format: text
Files: /usr/share/doc/modelloading/modelloading.text.gz

Format: HTML
Index: /usr/share/doc/modelloading/html/index.html
Files: /usr/share/doc/modelloading/html/*.html
