name: CI

on: [push]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: show PWD
      run: pwd

    - name: Install build dependencies
      run: sudo apt-get install -y devscripts debhelper qt5-qmake
      
    - name: try pack
      run: debuild -us -uc
